# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "AXYZdong"
repo_name: "reservoir-computing-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 2

publish_readme: True
publish_gitpage: True
#publish_wechat: False

# file paths
json_readme_path: './docs/rc-arxiv-daily.json'
json_gitpage_path: './docs/rc-arxiv-daily-web.json'
#json_wechat_path: './docs/rc-arxiv-daily-wechat.json'

md_gitpage_path: './docs/index.md'
md_readme_path: './README.md'

# keywords to search
keywords:
  "Reservoir Computing":
    filters:
      - 'ti:"Reservoir Computing" OR abs:"Reservoir Computing"'
      - 'ti:"reservoir computer" OR abs:"reservoir computer"'
      - 'ti:"physical reservoir" OR abs:"physical reservoir"'
      - 'ti:"dynamical reservoir" OR abs:"dynamical reservoir"'

  "ESN":
    filters:
      - 'ti:"Echo State Network" OR abs:"Echo State Network"'
      - 'ti:"Echo State Networks" OR abs:"Echo State Networks"'

  "LSM":
    filters:
      - 'ti:"Liquid State Machine" OR abs:"Liquid State Machine"'
      - 'ti:"Liquid State Machines" OR abs:"Liquid State Machines"'
