# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "AXYZdong"
repo_name: "reservoir-computing-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/rc-arxiv-daily.json'
json_gitpage_path: './docs/rc-arxiv-daily-web.json'
json_wechat_path: './docs/rc-arxiv-daily-wechat.json'

md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Reservoir Computing":
        filters: ["Reservoir Computing"]
    "ESN":
        filters: ["ESN", "Echo State Network"]
    "LSM":
        filters: ["LSM", "Liquid State Machine"]
